### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by kconnour** [kconnour/pyRT_DISORT#2]
I've tested the installation on Ubuntu 20.10 and MacOS Catalina 10.15.7 and it works. 

It failed on macOS 11.2.3 build 20D91. It fails to build the .so file but doesn't create an error.

**Comment by mjwolff** [comment]
work around for Big Sure:

# this will not compile the fortran code, but will set things up
pip -install .

# execute this command (it will compile the fortran, but it will not create the needed shared library by itself
python -m setup.py

# right above the usage statement (which is probably diagnostic of the problem, but i give up), you will see the fortran link 
# command.  copy and paste to the command line like so (assuming that you are in the installation directory):
/usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/disortmodule.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/fortranobject.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmpoy4pcd_5.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/BDREF.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/DISOBRDF.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/ERRPACK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/LAPACK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/LINPAK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/RDI1MACH.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/disort-f2pywrappers.o -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0 -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0/../../.. -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0/../../.. -lgfortran -o ./disort.cpython-39-darwin.so

# now run the install command again, it should move the shared library to the desired site-packages location.
pip install .

[elvis:lib/python3.9/site-packages] mwolff% ls -al | grep disort
-rwxr-xr-x    1 mwolff  staff  977528 Aug  8 10:35 disort.cpython-39-darwin.so

Successfully installed pyRT-DISORT-0.0.3
(vpyrt) [elvis:rt/disort/pyRT_DISORT] mwolff% python
Python 3.9.5 (default, May  7 2021, 21:28:16) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import disort
>>>

**Comment by kconnour** [comment]
Can you remind me, does this issue happen when executing `python -m pip install .`? I find that works but I got the same error on Ubuntu when using `python setup.py`. I don't know what `-m` would do if no module is provided.

**Comment by mjwolff** [comment]
I don’t recall it working properly in either version.  Basically, I have to cut-and-based the link command from the screen back to the terminal, which creates the library.  Running the install command then seems to put it in the right place.


On Feb 26, 2022, at 6:46 PM, kconnour ***@***.******@***.***>> wrote:



Can you remind me, does this issue happen when executing python -m pip install .? I find that works but I got the same error on Ubuntu when using python setup.py. I don't know what -m would do if no module is provided.

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkconnour%2FpyRT_DISORT%2Fissues%2F2%23issuecomment-1052372560&data=04%7C01%7Cmjwolff%40spacescience.org%7C47b7dd2adeed4e07437308d9f94fed61%7C3461589e91624c2e8e5b764489129af6%7C1%7C0%7C637814943976394162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iYcxoZ3pwBz%2Blgvqn83edFn%2Bfodc2h5m2uwdHlFumPw%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAKXHPB46E5SHXXXFVIWY2DU5EGXRANCNFSM43TYU7AA&data=04%7C01%7Cmjwolff%40spacescience.org%7C47b7dd2adeed4e07437308d9f94fed61%7C3461589e91624c2e8e5b764489129af6%7C1%7C0%7C637814943976394162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DWUNyTOhzbpXSOmWIbtMGezPkSQdgyQZjY7KgJ5yY0I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmjwolff%40spacescience.org%7C47b7dd2adeed4e07437308d9f94fed61%7C3461589e91624c2e8e5b764489129af6%7C1%7C0%7C637814943976394162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w4LVIgNMFwrR%2BQyJGj3LUjLfdOTEV0%2FQeFKERcOYQyo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmjwolff%40spacescience.org%7C47b7dd2adeed4e07437308d9f94fed61%7C3461589e91624c2e8e5b764489129af6%7C1%7C0%7C637814943976394162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DvxHk4Aby4hdAIUZbBKRawH3KyPPvkwCwAK8IQhP1QU%3D&reserved=0>.

**Comment by mjwolff** [comment]
here is some diagnostic output (install.log  attached). #14 

(vpyrt) mwolff@taus:~/test/pyRT_DISORT$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-yTrUTS/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04) 
(vpyrt) mwolff@taus:~/test/pyRT_DISORT$ python3 -m setup.py > install.log 2>&1 

[install.log](https://github.com/kconnour/pyRT_DISORT/files/8315164/install.log)

**Comment by YLeseigneur** [comment]
Hi,

I have quite the same issue on my Mac (12.2 Monterey).

After using `pip install .` and trying in python to `import pyrt` I got this error: 
`ImportError: dlopen(/Users/yleseign/miniconda3/envs/MIRS/lib/python3.10/site-packages/disort.so, 0x0002): tried: '/Users/yleseign/miniconda3/envs/MIRS/lib/python3.10/site-packages/disort.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/disort.so' (no such file), '/usr/lib/disort.so' (no such file)`

Then, I tried to follow your lines @mjwolff (see below), but I do not have a `/var/folders/ft` folder, only: `/02`, `/ny` or `/zz`. Do you know why? Could this be due to the way I have installed `gfortran`? (from binary files as explained here: [https://github.com/fxcoudert/gfortran-for-macOS/releases](https://github.com/fxcoudert/gfortran-for-macOS/releases)).

> ## work around for Big Sur:
> ### this will not compile the fortran code, but will set things up
> pip -install .
> 
> ### execute this command (it will compile the fortran, but it will not create the needed shared library by itself
> python -m setup.py
> 
> ### right above the usage statement (which is probably diagnostic of the problem, but i give up), you will see the fortran link command. copy and paste to the command line like so (assuming that you are in the installation directory):
> `/usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/disortmodule.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/fortranobject.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmpoy4pcd_5.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/BDREF.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/DISOBRDF.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/ERRPACK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/LAPACK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/LINPAK.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/Users/mwolff/src/rt/disort/pyRT_DISORT/disort4.0.99/RDI1MACH.o /var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/var/folders/ft/jtq2d1mn6950klgtpf83szxr0000z9/T/tmphgmoi6co/src.macosx-11.3-x86_64-3.9/disort-f2pywrappers.o -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0 -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0/../../.. -L/usr/local/lib/gcc/x86_64-apple-darwin19/10.2.0/../../.. -lgfortran -o ./disort.cpython-39-darwin.so`
> 
> ### now run the install command again, it should move the shared library to the desired site-packages location.
> pip install .
> 
> ```
> 
> [elvis:lib/python3.9/site-packages] mwolff% ls -al | grep disort
> -rwxr-xr-x    1 mwolff  staff  977528 Aug  8 10:35 disort.cpython-39-darwin.so
> 
> Successfully installed pyRT-DISORT-0.0.3
> (vpyrt) [elvis:rt/disort/pyRT_DISORT] mwolff% python
> Python 3.9.5 (default, May  7 2021, 21:28:16) 
> [Clang 12.0.5 (clang-1205.0.22.9)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import disort
> >>> 
> ```

**Comment by YLeseigneur** [comment]
Salut Mike,

Monterey 12.2.1 (Apple M1)

**Comment by mjwolff** [comment]
I see that this is being logged, so I will switch to English.

1) Is miniconda a fresh install?

2) I have had this problem for a different install on an m1 machine that I have.  With the M1, it seems to allow an option to run in a rosetta mode with x86_64 architecture.  From what I can tell, you will want to try to force condo to install natively…with something like:

conda activate native  
conda config --env --set subdir osx-arm64

See this thread.

https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple￼
How to specify the architecture or platform for a new conda environment? (Apple Silicon)
stackoverflow.com
 

Je serai en Angleterre (pour l’équipe NOMAD) jusqu’au jeudi prochaine, et puis un retour vers Paris.  Tu es où au moment?  LATMOS?

				—mike

**Comment by mjwolff** [comment]
Hi Yann,

Is there any chance that you hadn’t activated your env before you tried the import?  Are you able to upgrade your OS or is it constrained by LATMOS IT policies?

				—mike

**Comment by YLeseigneur** [comment]
Hi Mike,

No chance, I pay attention to activate the conda environment. Maybe it's a mismatch between `conda env` and native env which is not totally resolved by the procedure you referred to.

Yes, I can upgrade the OSX. I will do it during lunchtime and I will keep you in touch. (I guess I will also have to uninstall and reinstall `gfortran` with the adequate binary files.)

**Comment by kconnour** [comment]
I've separated the repositories into pyDISORT and pyRT_DISORT. Consequently, the FORTRAN compilation issue is no longer part of this repo and has seemingly been fixed in the other repo: https://github.com/kconnour/pyDISORT. If this issue persists, please raise an issue over there.
