### ISSUE TITLE
in consistency in units between output of column_density and input of the same quantity into rayleigh_co2

### ISSUE THREAD

**Issue by mjwolff** [kconnour/pyRT_DISORT#25]
### Bug description

pyrt.rayleigh_co2 wants column density in units m**-2 but pyrt.column_density outputs cm**-2. 

perhaps ensure that column_density returns m**-2

### Minimal working example

```
This is what I have to do to get the appropriate Rayleigh optical depth

```
column_density = pyrt.column_density(p_grid, T_grid, z_grid)
rayleigh_co2 = pyrt.rayleigh_co2(column_density*1.e4, wave_obs)

### Operating system

Mac OS Sonoma 14.3.1

### Python version

Python 3.11.8

### Priority

not, but a good idea

### Further information

this is not truly a bug, but it will create that for people that do not to bench mark calculations in column density and Rayleigh optical depths.

**Comment by kconnour** [comment]
This should be fixed with #26.
